### ISSUE TITLE
Center figcaption when align=center is set for figure

### ISSUE THREAD

**Issue by GYHHAHA** [executablebooks/myst-theme#106]
### Context

Now, figcaption is always starting at the left side, regardless of the align setting for figure:
![28 05 2023_19 10 48_REC](https://github.com/executablebooks/myst-theme/assets/41546976/8fa3b7a2-1046-4a94-8bbe-44e219cb512f)
For better visual experience, it's a good choice for figcaption to set as `text-center` when figure align=center, especially when the screen is relatively wide:
![28 05 2023_19 15 17_REC](https://github.com/executablebooks/myst-theme/assets/41546976/6877c011-635c-4a10-8282-6a8ade1c426c)

**Comment by GYHHAHA** [comment]
The first solution comes to my mind is to use
```css
img + p {
  position: relative;
  left: 50%;
  transform: translateX(-50%);
  text-align: center;
}
```
Although this works, I still wish this can be done in a component level.
