### ISSUE TITLE
`binder` settings generate incorrect url if `ref` missing

### ISSUE THREAD

**Issue by stevejpurves** [executablebooks/myst-theme#131]
### Describe the bug

**context**
When I setup biner using the following fields:

```
  github: username/repo
  thebe:
    binder:
      repo: username/repo
```

an error occurs and the binder url is malformed

```
https://mybinder.org/build/gh/username/repo/undefined
```

Note that the following settings work as expected:

```
  github: username/repo
  thebe:
    binder: true
```

as does

```
  github: username/repo
  thebe:
    binder:
      repo: username/repo
      ref: HEAD
```

**expectation**
I expected binder to launch correctly

**bug**
But instead binder fails with no UI feedback

```console
$ jupyter-book build mybook
ERROR ...
```

**problem**
This is a problem for people using binder as there is a failure and no feedback.

### Reproduce the bug

Setup thebe as so:

```
  github: username/repo
  thebe:
    binder:
      repo: username/repo
```

run `myst start`
navigate to a notebook
click the power button
