### ISSUE TITLE
Provide nesting in TOC for sections

### ISSUE THREAD

**Issue by stevejpurves** [executablebooks/myst-theme#226]
### Context

Given a valid `_toc.yml` of:

```
format: jb-book
root: index
parts:
  - caption: Tutorials
    chapters:
      - file: tutorial1
      - file: tutorial2
        sections:
          - file: tutorial2.1
          - file: tutorial2.2
      - file: tutorial3
```

`mystmd` produces a TOC data structure that reflects grouping and nesting via the `level` field:

```
"pages": [
{
"title": "Tutorials",
"level": 1
},
{
"slug": "tutorial1",
"title": "TUTORIAL 1",
...,
"level": 2
},
{
"slug": "tutorial2",
"title": "TUTORIAL 2",
...,
"level": 2
},
{
"slug": "tutorial2-1",
"title": "TUTORIAL 2.1",
...,
"level": 3
},
{
"slug": "tutorial2-2",
"title": "TUTORIAL 2.2",
...,
"level": 3
},
{
"slug": "tutorial3",
"title": "TUTORIAL 3",
...,
"level": 2
}
]
```

But the myst theme TOC does not show this nesting.

![image](https://github.com/executablebooks/myst-theme/assets/1473646/45eb00c8-257a-41c2-9667-814114e31a2d)

### Proposal

1. nest the TOC items in line with the `level` reported in the data structure
2. enable expand/collapse controls for items `level > 2`
