### ISSUE TITLE
Project-level download button configuration for the book theme

### ISSUE THREAD

**Issue by choldgraf** [executablebooks/myst-theme#352]
### Context

In https://github.com/executablebooks/mystmd/pull/1064 we're describing some of the new download functionality. In the process we realized that the project-level configuration doesn't yet have any effect on the book theme. You still must manually specify the download configuration _per-page_.

### Proposal

I'd like to be able to specify a download configuration one time, and have it apply to all pages in a book. For example:

In `myst.yml`

```yaml
project:
  download:
    - file: pathtomybook.pdf
    - id: someid
```

Any page-level download metadata would then override this
